#!/bin/bash
# Script to auto set pasword

# Vars
PORT=5433
TMP_FILE=database.set.password.sql
DATABASE="auth_jwt"
USER="auth-jwt-server"

if [ ! -z "$2" ]
then
  # Set port to arg
	PORT=$2
fi

echo "Please enter a password for the database auth:jwt, user auth-jwt-server, below:"
read password # Unsecure so you know it went through
echo "Creating script..."
echo "--
-- FILE AUTOGENERATED BY ./sql/db_set_pwd.sh (part of Authentication macroservice, jwt microservice)
-- DO NOT MODIFY
-- Please use the script to regenerate the file
--
\connect $DATABASE
ALTER USER \"$USER\" PASSWORD '$password';" > $TMP_FILE

echo "Running command to change the database..."
echo "- Using superuser \"postgres\""
echo "- Port: $PORT"
echo "Use ./db_set_pwd.sh <user> <port> to modify this values."
psql -U postgres -p 5433 -f $TMP_FILE

echo "Cleaning up..."
rm -v $TMP_FILE