# Gitlab config
stages:
  - build
  - test # Test & lint
  - document # Generate documentation
  - deploy # Deploy documentation

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

# Job 0: Build (npm install)
yarn-install:
  stage: build
  image: node:lts
  script:
    - yarn install

# Job 1: test
ts-lint:
  stage: test
  image: node:lts
  script:
    - yarn run tslint --project ./login --config ./tslint.json

mocha:
  stage: test
  image: node:lts
  script:
    - yarn test