# Gitlab config
stages:
  - prepare
  - test # Test & lint
  - document # Generate documentation
  - deploy # Deploy documentation

# Database
services:
  - postgres:latest

variables:
  RYKAN_DB_ENVIRONMENT: ci
  POSTGRES_DB: users
  POSTGRES_USER: rykan-testing
  POSTGRES_PASSWORD: ""

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

# Job 0: Build (npm install)
yarn-install:
  stage: prepare
  image: node:lts
  script:
    - yarn install
db.login.build:
  stage: prepare
  image: postgres:latest
  script:
    - psql -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h "postgres" -1 -f login/ci/Database.sql


# Job 1: test
ts-lint:
  stage: test
  image: node:lts
  script:
    - yarn run tslint --project ./login --config ./tslint.json

login.mocha:
  stage: test
  image: node:lts
  script:
    - cd login && yarn test