# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  checkout_code:
    docker:
      - image: circleci/node:latest
    working_directory: ~/rykan-auth
    steps:
      - checkout
      - save_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/rykan-auth
  yarn-install:
    executor:
      name: node/default
      tag: lts

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/rykan-auth

    steps:
      # Download and cache dependencies
      - restore_cache:
          key: repo-{{ .Environment.CIRCLE_SHA1 }}
      - node/with-cache:
          dir: ~/rykan-auth
          steps:
              - run: yarn install
      - save_cache:
          key: repo-{{ checksum package.json }}
          paths:
            - ~/rykan-auth/login/node_modules
            - ~/rykan-auth/jwt/node_modules

workflows:
  version: 2
  login:
    jobs:
      - checkout_code
      - yarn-install:
          requires:
            - checkout_code