#%RAML 1.0 Library
usage: Includes common traits, schemas etc used throughout the API definitions

traits:
  messageReturn: !include ./traits/message-return.raml
  missingField: !include ./traits/field-missing.raml
