// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.rykan.protobuf.mq.general;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserEventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:general.user.events.UserEvent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *&#47; UUID of user
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    java.lang.String getUuid();
    /**
     * <pre>
     *&#47; UUID of user
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>.general.user.events.UserEvent.UserEventMessageType event = 2;</code>
     */
    int getEventValue();
    /**
     * <code>.general.user.events.UserEvent.UserEventMessageType event = 2;</code>
     */
    com.rykan.protobuf.mq.general.User.UserEvent.UserEventMessageType getEvent();
  }
  /**
   * <pre>
   **
   * Message format for when user made.
   * </pre>
   *
   * Protobuf type {@code general.user.events.UserEvent}
   */
  public  static final class UserEvent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:general.user.events.UserEvent)
      UserEventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UserEvent.newBuilder() to construct.
    private UserEvent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserEvent() {
      uuid_ = "";
      event_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new UserEvent();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UserEvent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              uuid_ = s;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              event_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.rykan.protobuf.mq.general.User.internal_static_general_user_events_UserEvent_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.rykan.protobuf.mq.general.User.internal_static_general_user_events_UserEvent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.rykan.protobuf.mq.general.User.UserEvent.class, com.rykan.protobuf.mq.general.User.UserEvent.Builder.class);
    }

    /**
     * Protobuf enum {@code general.user.events.UserEvent.UserEventMessageType}
     */
    public enum UserEventMessageType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>CREATE = 0;</code>
       */
      CREATE(0),
      /**
       * <code>DELETE = 1;</code>
       */
      DELETE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>CREATE = 0;</code>
       */
      public static final int CREATE_VALUE = 0;
      /**
       * <code>DELETE = 1;</code>
       */
      public static final int DELETE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static UserEventMessageType valueOf(int value) {
        return forNumber(value);
      }

      public static UserEventMessageType forNumber(int value) {
        switch (value) {
          case 0: return CREATE;
          case 1: return DELETE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<UserEventMessageType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          UserEventMessageType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<UserEventMessageType>() {
              public UserEventMessageType findValueByNumber(int number) {
                return UserEventMessageType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.rykan.protobuf.mq.general.User.UserEvent.getDescriptor().getEnumTypes().get(0);
      }

      private static final UserEventMessageType[] VALUES = values();

      public static UserEventMessageType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private UserEventMessageType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:general.user.events.UserEvent.UserEventMessageType)
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <pre>
     *&#47; UUID of user
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *&#47; UUID of user
     * </pre>
     *
     * <code>string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_FIELD_NUMBER = 2;
    private int event_;
    /**
     * <code>.general.user.events.UserEvent.UserEventMessageType event = 2;</code>
     */
    public int getEventValue() {
      return event_;
    }
    /**
     * <code>.general.user.events.UserEvent.UserEventMessageType event = 2;</code>
     */
    public com.rykan.protobuf.mq.general.User.UserEvent.UserEventMessageType getEvent() {
      @SuppressWarnings("deprecation")
      com.rykan.protobuf.mq.general.User.UserEvent.UserEventMessageType result = com.rykan.protobuf.mq.general.User.UserEvent.UserEventMessageType.valueOf(event_);
      return result == null ? com.rykan.protobuf.mq.general.User.UserEvent.UserEventMessageType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUuidBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (event_ != com.rykan.protobuf.mq.general.User.UserEvent.UserEventMessageType.CREATE.getNumber()) {
        output.writeEnum(2, event_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (event_ != com.rykan.protobuf.mq.general.User.UserEvent.UserEventMessageType.CREATE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, event_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.rykan.protobuf.mq.general.User.UserEvent)) {
        return super.equals(obj);
      }
      com.rykan.protobuf.mq.general.User.UserEvent other = (com.rykan.protobuf.mq.general.User.UserEvent) obj;

      if (!getUuid()
          .equals(other.getUuid())) return false;
      if (event_ != other.event_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + EVENT_FIELD_NUMBER;
      hash = (53 * hash) + event_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.rykan.protobuf.mq.general.User.UserEvent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rykan.protobuf.mq.general.User.UserEvent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rykan.protobuf.mq.general.User.UserEvent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rykan.protobuf.mq.general.User.UserEvent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rykan.protobuf.mq.general.User.UserEvent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.rykan.protobuf.mq.general.User.UserEvent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.rykan.protobuf.mq.general.User.UserEvent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rykan.protobuf.mq.general.User.UserEvent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rykan.protobuf.mq.general.User.UserEvent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.rykan.protobuf.mq.general.User.UserEvent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.rykan.protobuf.mq.general.User.UserEvent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.rykan.protobuf.mq.general.User.UserEvent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.rykan.protobuf.mq.general.User.UserEvent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     **
     * Message format for when user made.
     * </pre>
     *
     * Protobuf type {@code general.user.events.UserEvent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:general.user.events.UserEvent)
        com.rykan.protobuf.mq.general.User.UserEventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.rykan.protobuf.mq.general.User.internal_static_general_user_events_UserEvent_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.rykan.protobuf.mq.general.User.internal_static_general_user_events_UserEvent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.rykan.protobuf.mq.general.User.UserEvent.class, com.rykan.protobuf.mq.general.User.UserEvent.Builder.class);
      }

      // Construct using com.rykan.protobuf.mq.general.User.UserEvent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uuid_ = "";

        event_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.rykan.protobuf.mq.general.User.internal_static_general_user_events_UserEvent_descriptor;
      }

      @java.lang.Override
      public com.rykan.protobuf.mq.general.User.UserEvent getDefaultInstanceForType() {
        return com.rykan.protobuf.mq.general.User.UserEvent.getDefaultInstance();
      }

      @java.lang.Override
      public com.rykan.protobuf.mq.general.User.UserEvent build() {
        com.rykan.protobuf.mq.general.User.UserEvent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.rykan.protobuf.mq.general.User.UserEvent buildPartial() {
        com.rykan.protobuf.mq.general.User.UserEvent result = new com.rykan.protobuf.mq.general.User.UserEvent(this);
        result.uuid_ = uuid_;
        result.event_ = event_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.rykan.protobuf.mq.general.User.UserEvent) {
          return mergeFrom((com.rykan.protobuf.mq.general.User.UserEvent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.rykan.protobuf.mq.general.User.UserEvent other) {
        if (other == com.rykan.protobuf.mq.general.User.UserEvent.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.event_ != 0) {
          setEventValue(other.getEventValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.rykan.protobuf.mq.general.User.UserEvent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.rykan.protobuf.mq.general.User.UserEvent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <pre>
       *&#47; UUID of user
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *&#47; UUID of user
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *&#47; UUID of user
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; UUID of user
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *&#47; UUID of user
       * </pre>
       *
       * <code>string uuid = 1;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uuid_ = value;
        onChanged();
        return this;
      }

      private int event_ = 0;
      /**
       * <code>.general.user.events.UserEvent.UserEventMessageType event = 2;</code>
       */
      public int getEventValue() {
        return event_;
      }
      /**
       * <code>.general.user.events.UserEvent.UserEventMessageType event = 2;</code>
       */
      public Builder setEventValue(int value) {
        event_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.general.user.events.UserEvent.UserEventMessageType event = 2;</code>
       */
      public com.rykan.protobuf.mq.general.User.UserEvent.UserEventMessageType getEvent() {
        @SuppressWarnings("deprecation")
        com.rykan.protobuf.mq.general.User.UserEvent.UserEventMessageType result = com.rykan.protobuf.mq.general.User.UserEvent.UserEventMessageType.valueOf(event_);
        return result == null ? com.rykan.protobuf.mq.general.User.UserEvent.UserEventMessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.general.user.events.UserEvent.UserEventMessageType event = 2;</code>
       */
      public Builder setEvent(com.rykan.protobuf.mq.general.User.UserEvent.UserEventMessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        event_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.general.user.events.UserEvent.UserEventMessageType event = 2;</code>
       */
      public Builder clearEvent() {
        
        event_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:general.user.events.UserEvent)
    }

    // @@protoc_insertion_point(class_scope:general.user.events.UserEvent)
    private static final com.rykan.protobuf.mq.general.User.UserEvent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.rykan.protobuf.mq.general.User.UserEvent();
    }

    public static com.rykan.protobuf.mq.general.User.UserEvent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserEvent>
        PARSER = new com.google.protobuf.AbstractParser<UserEvent>() {
      @java.lang.Override
      public UserEvent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserEvent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserEvent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserEvent> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.rykan.protobuf.mq.general.User.UserEvent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_general_user_events_UserEvent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_general_user_events_UserEvent_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\023general.user.events\"\215\001\n\tUs" +
      "erEvent\022\014\n\004uuid\030\001 \001(\t\022B\n\005event\030\002 \001(\01623.g" +
      "eneral.user.events.UserEvent.UserEventMe" +
      "ssageType\".\n\024UserEventMessageType\022\n\n\006CRE" +
      "ATE\020\000\022\n\n\006DELETE\020\001B%\n\035com.rykan.protobuf." +
      "mq.generalB\004Userb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_general_user_events_UserEvent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_general_user_events_UserEvent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_general_user_events_UserEvent_descriptor,
        new java.lang.String[] { "Uuid", "Event", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
