kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-volume-2
  labels:
    type: local
    app: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/D/Users\\Kishan\\Documents\\Projects\\CONFIDENTIAL\\rykan\\authentication\\login\\kube\\storage"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-pv-claim-2
  labels:
    app: postgres
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: "postgres-pv-volume-2"