#%RAML 1.0 SecurityScheme
description: Uses XSRF to secure endpoints, namely pre-login actions
displayName: XSRF Security
type: x-xsrf

describedBy:
  headers:
    X-XSRF-TOKEN:
      type: number
      description: |
        Contains the XSRF token, issued in a cookie or in a access token
        issuing response.
        Tokens are verified by using the double submit cookie method.
